package com.rhys.financetracker.data.backup

import com.rhys.financetracker.data.local.entity.AccountEntity
import com.rhys.financetracker.data.local.entity.CategoryEntity
import com.rhys.financetracker.data.local.entity.ExternalDataEntity
import com.rhys.financetracker.data.local.entity.MonthlySnapshotEntity
import com.rhys.financetracker.data.local.entity.PersonEntity
import com.rhys.financetracker.data.local.entity.RecurringRuleEntity
import com.rhys.financetracker.data.local.entity.SavingsGoalEntity
import com.rhys.financetracker.data.local.entity.TransactionEntity
import com.rhys.financetracker.domain.model.AccountType
import com.rhys.financetracker.domain.model.CategoryKind
import com.rhys.financetracker.domain.model.Frequency
import com.rhys.financetracker.domain.model.RecurrenceMode
import com.rhys.financetracker.domain.model.RecordSource
import com.rhys.financetracker.domain.model.TransactionType
import org.json.JSONArray
import org.json.JSONObject
import java.time.LocalDate
import javax.inject.Inject
import javax.inject.Singleton

/**
 * Converts entities to and from the backup JSON.
 *
 * The mapping is written out by hand rather than generated by reflection so
 * that renaming a Kotlin property can never silently change the file format —
 * a backup taken today must still restore in five years' time.
 *
 * Reads are forgiving: every `opt…` call has a default, so a file written by an
 * older version restores without complaint.
 */
@Singleton
class BackupSerializer @Inject constructor() {

    // -------------------------------------------------------------- people

    fun personToJson(person: PersonEntity): JSONObject = JSONObject().apply {
        put("id", person.id)
        put("name", person.name)
        put("colorHex", person.colorHex)
        put("isShared", person.isShared)
        put("sortOrder", person.sortOrder)
        putOpt("notes", person.notes)
        put("isArchived", person.isArchived)
        put("createdAt", person.createdAt)
        put("updatedAt", person.updatedAt)
    }

    fun personFromJson(json: JSONObject): PersonEntity = PersonEntity(
        id = json.optLong("id", 0L),
        name = json.optString("name", "Unnamed"),
        colorHex = json.optString("colorHex", "#455A64"),
        isShared = json.optBoolean("isShared", false),
        sortOrder = json.optInt("sortOrder", 0),
        notes = json.optStringOrNull("notes"),
        isArchived = json.optBoolean("isArchived", false),
        createdAt = json.optLong("createdAt", System.currentTimeMillis()),
        updatedAt = json.optLong("updatedAt", System.currentTimeMillis()),
    )

    // ------------------------------------------------------------ accounts

    fun accountToJson(account: AccountEntity): JSONObject = JSONObject().apply {
        put("id", account.id)
        put("name", account.name)
        put("type", account.type.name)
        putOpt("personId", account.personId)
        put("openingBalanceMinor", account.openingBalanceMinor)
        put("openingBalanceDate", account.openingBalanceDate.toString())
        put("currencyCode", account.currencyCode)
        put("overdraftLimitMinor", account.overdraftLimitMinor)
        putOpt("lowBalanceThresholdMinor", account.lowBalanceThresholdMinor)
        putOpt("creditLimitMinor", account.creditLimitMinor)
        putOpt("interestRatePercent", account.interestRatePercent)
        put("colorHex", account.colorHex)
        put("includeInNetWorth", account.includeInNetWorth)
        putOpt("countsAsSavings", account.countsAsSavings)
        put("isShared", account.isShared)
        put("sortOrder", account.sortOrder)
        putOpt("notes", account.notes)
        put("isArchived", account.isArchived)
        put("createdAt", account.createdAt)
        put("updatedAt", account.updatedAt)
    }

    fun accountFromJson(json: JSONObject): AccountEntity = AccountEntity(
        id = json.optLong("id", 0L),
        name = json.optString("name", "Account"),
        type = json.optEnum("type", AccountType.OTHER) { AccountType.valueOf(it) },
        personId = json.optLongOrNull("personId"),
        openingBalanceMinor = json.optLong("openingBalanceMinor", 0L),
        openingBalanceDate = json.optDate("openingBalanceDate") ?: LocalDate.now(),
        currencyCode = json.optString("currencyCode", "GBP"),
        overdraftLimitMinor = json.optLong("overdraftLimitMinor", 0L),
        lowBalanceThresholdMinor = json.optLongOrNull("lowBalanceThresholdMinor"),
        creditLimitMinor = json.optLongOrNull("creditLimitMinor"),
        interestRatePercent = if (json.has("interestRatePercent") &&
            !json.isNull("interestRatePercent")
        ) {
            json.optDouble("interestRatePercent")
        } else {
            null
        },
        colorHex = json.optString("colorHex", "#455A64"),
        includeInNetWorth = json.optBoolean("includeInNetWorth", true),
        countsAsSavings = if (json.has("countsAsSavings")) {
            json.optBoolean("countsAsSavings")
        } else {
            null
        },
        isShared = json.optBoolean("isShared", false),
        sortOrder = json.optInt("sortOrder", 0),
        notes = json.optStringOrNull("notes"),
        isArchived = json.optBoolean("isArchived", false),
        createdAt = json.optLong("createdAt", System.currentTimeMillis()),
        updatedAt = json.optLong("updatedAt", System.currentTimeMillis()),
    )

    // ---------------------------------------------------------- categories

    fun categoryToJson(category: CategoryEntity): JSONObject = JSONObject().apply {
        put("id", category.id)
        put("name", category.name)
        put("kind", category.kind.name)
        put("colorHex", category.colorHex)
        putOpt("iconKey", category.iconKey)
        putOpt("parentId", category.parentId)
        putOpt("monthlyBudgetMinor", category.monthlyBudgetMinor)
        put("sortOrder", category.sortOrder)
        put("isSystem", category.isSystem)
        put("isArchived", category.isArchived)
        put("createdAt", category.createdAt)
        put("updatedAt", category.updatedAt)
    }

    fun categoryFromJson(json: JSONObject): CategoryEntity = CategoryEntity(
        id = json.optLong("id", 0L),
        name = json.optString("name", "Category"),
        kind = json.optEnum("kind", CategoryKind.EXPENSE) { CategoryKind.valueOf(it) },
        colorHex = json.optString("colorHex", "#455A64"),
        iconKey = json.optStringOrNull("iconKey"),
        parentId = json.optLongOrNull("parentId"),
        monthlyBudgetMinor = json.optLongOrNull("monthlyBudgetMinor"),
        sortOrder = json.optInt("sortOrder", 0),
        isSystem = json.optBoolean("isSystem", false),
        isArchived = json.optBoolean("isArchived", false),
        createdAt = json.optLong("createdAt", System.currentTimeMillis()),
        updatedAt = json.optLong("updatedAt", System.currentTimeMillis()),
    )

    // -------------------------------------------------------- transactions

    fun transactionToJson(transaction: TransactionEntity): JSONObject = JSONObject().apply {
        put("id", transaction.id)
        put("amountMinor", transaction.amountMinor)
        put("type", transaction.type.name)
        put("date", transaction.date.toString())
        put("description", transaction.description)
        put("accountId", transaction.accountId)
        putOpt("transferAccountId", transaction.transferAccountId)
        putOpt("categoryId", transaction.categoryId)
        putOpt("personId", transaction.personId)
        putOpt("recurringRuleId", transaction.recurringRuleId)
        putOpt("savingsGoalId", transaction.savingsGoalId)
        putOpt("notes", transaction.notes)
        put("isConfirmed", transaction.isConfirmed)
        put("isCleared", transaction.isCleared)
        putOpt("tags", transaction.tags)
        // Both of these decide what a later import does with the row. Without
        // the fingerprint, re-importing a statement after a restore adds every
        // row a second time; without the source, everything restored looks
        // hand-typed and the protection a bank record has is lost.
        putOpt("importHash", transaction.importHash)
        put("source", transaction.source.name)
        put("isArchived", transaction.isArchived)
        put("createdAt", transaction.createdAt)
        put("updatedAt", transaction.updatedAt)
    }

    fun transactionFromJson(json: JSONObject): TransactionEntity = TransactionEntity(
        id = json.optLong("id", 0L),
        amountMinor = json.optLong("amountMinor", 0L),
        type = json.optEnum("type", TransactionType.EXPENSE) { TransactionType.valueOf(it) },
        date = json.optDate("date") ?: LocalDate.now(),
        description = json.optString("description", "Transaction"),
        accountId = json.optLong("accountId", 0L),
        transferAccountId = json.optLongOrNull("transferAccountId"),
        categoryId = json.optLongOrNull("categoryId"),
        personId = json.optLongOrNull("personId"),
        recurringRuleId = json.optLongOrNull("recurringRuleId"),
        savingsGoalId = json.optLongOrNull("savingsGoalId"),
        notes = json.optStringOrNull("notes"),
        isConfirmed = json.optBoolean("isConfirmed", true),
        isCleared = json.optBoolean("isCleared", true),
        tags = json.optStringOrNull("tags"),
        importHash = json.optStringOrNull("importHash"),
        // A backup written before this was recorded restores as UNKNOWN, the
        // weakest source, so an old backup is corrected by a statement rather
        // than shielded from one.
        source = json.optEnum("source", RecordSource.UNKNOWN) { RecordSource.valueOf(it) },
        isArchived = json.optBoolean("isArchived", false),
        createdAt = json.optLong("createdAt", System.currentTimeMillis()),
        updatedAt = json.optLong("updatedAt", System.currentTimeMillis()),
    )

    // ------------------------------------------------------------ recurring

    fun recurringToJson(rule: RecurringRuleEntity): JSONObject = JSONObject().apply {
        put("id", rule.id)
        put("name", rule.name)
        put("amountMinor", rule.amountMinor)
        put("type", rule.type.name)
        put("frequency", rule.frequency.name)
        put("interval", rule.interval)
        put("startDate", rule.startDate.toString())
        putOpt("endDate", rule.endDate?.toString())
        putOpt("maxOccurrences", rule.maxOccurrences)
        put("occurrencesGenerated", rule.occurrencesGenerated)
        put("nextDueDate", rule.nextDueDate.toString())
        putOpt("lastGeneratedDate", rule.lastGeneratedDate?.toString())
        put("accountId", rule.accountId)
        putOpt("transferAccountId", rule.transferAccountId)
        putOpt("categoryId", rule.categoryId)
        putOpt("personId", rule.personId)
        putOpt("savingsGoalId", rule.savingsGoalId)
        put("mode", rule.mode.name)
        putOpt("reminderDaysBefore", rule.reminderDaysBefore)
        put("isVariableAmount", rule.isVariableAmount)
        putOpt("notes", rule.notes)
        put("isPaused", rule.isPaused)
        put("isArchived", rule.isArchived)
        put("createdAt", rule.createdAt)
        put("updatedAt", rule.updatedAt)
    }

    fun recurringFromJson(json: JSONObject): RecurringRuleEntity {
        val start = json.optDate("startDate") ?: LocalDate.now()
        return RecurringRuleEntity(
            id = json.optLong("id", 0L),
            name = json.optString("name", "Recurring payment"),
            amountMinor = json.optLong("amountMinor", 0L),
            type = json.optEnum("type", TransactionType.EXPENSE) { TransactionType.valueOf(it) },
            frequency = json.optEnum("frequency", Frequency.MONTHLY) { Frequency.valueOf(it) },
            interval = json.optInt("interval", 1),
            startDate = start,
            endDate = json.optDate("endDate"),
            maxOccurrences = json.optIntOrNull("maxOccurrences"),
            occurrencesGenerated = json.optInt("occurrencesGenerated", 0),
            nextDueDate = json.optDate("nextDueDate") ?: start,
            lastGeneratedDate = json.optDate("lastGeneratedDate"),
            accountId = json.optLong("accountId", 0L),
            transferAccountId = json.optLongOrNull("transferAccountId"),
            categoryId = json.optLongOrNull("categoryId"),
            personId = json.optLongOrNull("personId"),
            savingsGoalId = json.optLongOrNull("savingsGoalId"),
            mode = json.optEnum("mode", RecurrenceMode.AUTO_POST) { RecurrenceMode.valueOf(it) },
            reminderDaysBefore = json.optIntOrNull("reminderDaysBefore"),
            isVariableAmount = json.optBoolean("isVariableAmount", false),
            notes = json.optStringOrNull("notes"),
            isPaused = json.optBoolean("isPaused", false),
            isArchived = json.optBoolean("isArchived", false),
            createdAt = json.optLong("createdAt", System.currentTimeMillis()),
            updatedAt = json.optLong("updatedAt", System.currentTimeMillis()),
        )
    }

    // ---------------------------------------------------------------- goals

    fun goalToJson(goal: SavingsGoalEntity): JSONObject = JSONObject().apply {
        put("id", goal.id)
        put("name", goal.name)
        put("targetAmountMinor", goal.targetAmountMinor)
        put("manualAdjustmentMinor", goal.manualAdjustmentMinor)
        put("monthlyContributionMinor", goal.monthlyContributionMinor)
        putOpt("targetDate", goal.targetDate?.toString())
        put("startDate", goal.startDate.toString())
        putOpt("accountId", goal.accountId)
        putOpt("personId", goal.personId)
        put("colorHex", goal.colorHex)
        putOpt("iconKey", goal.iconKey)
        putOpt("notes", goal.notes)
        put("sortOrder", goal.sortOrder)
        put("isAchieved", goal.isAchieved)
        put("isArchived", goal.isArchived)
        put("createdAt", goal.createdAt)
        put("updatedAt", goal.updatedAt)
    }

    fun goalFromJson(json: JSONObject): SavingsGoalEntity = SavingsGoalEntity(
        id = json.optLong("id", 0L),
        name = json.optString("name", "Savings goal"),
        targetAmountMinor = json.optLong("targetAmountMinor", 0L),
        manualAdjustmentMinor = json.optLong("manualAdjustmentMinor", 0L),
        monthlyContributionMinor = json.optLong("monthlyContributionMinor", 0L),
        targetDate = json.optDate("targetDate"),
        startDate = json.optDate("startDate") ?: LocalDate.now(),
        accountId = json.optLongOrNull("accountId"),
        personId = json.optLongOrNull("personId"),
        colorHex = json.optString("colorHex", "#1B5E4B"),
        iconKey = json.optStringOrNull("iconKey"),
        notes = json.optStringOrNull("notes"),
        sortOrder = json.optInt("sortOrder", 0),
        isAchieved = json.optBoolean("isAchieved", false),
        isArchived = json.optBoolean("isArchived", false),
        createdAt = json.optLong("createdAt", System.currentTimeMillis()),
        updatedAt = json.optLong("updatedAt", System.currentTimeMillis()),
    )

    // ------------------------------------------------------------ snapshots

    fun snapshotToJson(snapshot: MonthlySnapshotEntity): JSONObject = JSONObject().apply {
        put("id", snapshot.id)
        put("yearMonth", snapshot.yearMonth)
        put("accountId", snapshot.accountId)
        put("openingBalanceMinor", snapshot.openingBalanceMinor)
        put("closingBalanceMinor", snapshot.closingBalanceMinor)
        put("totalIncomeMinor", snapshot.totalIncomeMinor)
        put("totalExpenseMinor", snapshot.totalExpenseMinor)
        put("totalTransfersInMinor", snapshot.totalTransfersInMinor)
        put("totalTransfersOutMinor", snapshot.totalTransfersOutMinor)
        put("transactionCount", snapshot.transactionCount)
        put("createdAt", snapshot.createdAt)
    }

    fun snapshotFromJson(json: JSONObject): MonthlySnapshotEntity = MonthlySnapshotEntity(
        id = json.optLong("id", 0L),
        yearMonth = json.optString("yearMonth", ""),
        accountId = json.optLong("accountId", 0L),
        openingBalanceMinor = json.optLong("openingBalanceMinor", 0L),
        closingBalanceMinor = json.optLong("closingBalanceMinor", 0L),
        totalIncomeMinor = json.optLong("totalIncomeMinor", 0L),
        totalExpenseMinor = json.optLong("totalExpenseMinor", 0L),
        totalTransfersInMinor = json.optLong("totalTransfersInMinor", 0L),
        totalTransfersOutMinor = json.optLong("totalTransfersOutMinor", 0L),
        transactionCount = json.optInt("transactionCount", 0),
        createdAt = json.optLong("createdAt", System.currentTimeMillis()),
    )

    // -------------------------------------------------------- external data

    fun externalToJson(entry: ExternalDataEntity): JSONObject = JSONObject().apply {
        put("key", entry.key)
        put("value", entry.value)
        put("unit", entry.unit)
        put("source", entry.source)
        put("isManual", entry.isManual)
        put("fetchedAt", entry.fetchedAt)
        putOpt("lastError", entry.lastError)
    }

    fun externalFromJson(json: JSONObject): ExternalDataEntity = ExternalDataEntity(
        key = json.optString("key", ""),
        value = json.optString("value", ""),
        unit = json.optString("unit", ""),
        source = json.optString("source", ""),
        isManual = json.optBoolean("isManual", true),
        fetchedAt = json.optLong("fetchedAt", System.currentTimeMillis()),
        lastError = json.optStringOrNull("lastError"),
    )

    /** Reads a JSON array into a list, skipping any element that will not parse. */
    fun <T> readArray(array: JSONArray?, parse: (JSONObject) -> T): List<T> {
        if (array == null) return emptyList()
        val result = mutableListOf<T>()
        for (index in 0 until array.length()) {
            val item = array.optJSONObject(index) ?: continue
            runCatching { parse(item) }.onSuccess { result += it }
        }
        return result
    }

    fun <T> writeArray(items: List<T>, convert: (T) -> JSONObject): JSONArray =
        JSONArray().also { array -> items.forEach { array.put(convert(it)) } }
}

// ----------------------------------------------------- JSONObject helpers

/** `optString` returns "" for a missing key; this returns null, which is what entities expect. */
internal fun JSONObject.optStringOrNull(key: String): String? =
    if (!has(key) || isNull(key)) null else optString(key).takeIf { it.isNotEmpty() }

internal fun JSONObject.optLongOrNull(key: String): Long? =
    if (!has(key) || isNull(key)) null else optLong(key)

internal fun JSONObject.optIntOrNull(key: String): Int? =
    if (!has(key) || isNull(key)) null else optInt(key)

internal fun JSONObject.optDate(key: String): LocalDate? =
    optStringOrNull(key)?.let { runCatching { LocalDate.parse(it) }.getOrNull() }

/** Reads an enum by name, falling back to [fallback] if the name is unknown. */
internal fun <T : Enum<T>> JSONObject.optEnum(key: String, fallback: T, parse: (String) -> T): T =
    optStringOrNull(key)?.let { runCatching { parse(it) }.getOrNull() } ?: fallback
